# Generated by Django 5.1.3 on 2024-11-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='borrowed_date',
            new_name='borrow_date',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='returned_date',
            new_name='return_date',
        ),
    ]
