# Generated by Django 5.1.3 on 2024-11-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_borrowed_date_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='borrow_date',
            new_name='borrowed_date',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='return_date',
            new_name='returned_date',
        ),
    ]
