# Generated by Django 5.1.4 on 2025-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_borrow_date_borrow_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrow',
            constraint=models.CheckConstraint(condition=models.Q(('is_borrowed', False), ('returned_date__isnull', True), _connector='OR'), name='borrow_returned_implies_not_borrowed_check'),
        ),
    ]
