# Generated by Django 5.1.4 on 2025-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_borrow_borrow_returned_implies_not_borrowed_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
