# Generated by Django 5.1.4 on 2025-04-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_borrow_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author'),
        ),
        migrations.AddConstraint(
            model_name='borrow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_borrowed', True)), fields=('book',), name='borrow_unique_active_borrow_per_book'),
        ),
    ]
